# work dir
work_dir: "."
result_dir: "result"

# inputs
hisat2_index: "genome/index_hisat2/genome_Ac"
gtf: "genome/GCF_029169275.1/genomic.gtf"
dir_fastq: "fastq_data"
design_matrix: "design_matrix.csv"

# outputs
dir_bam: "bam/"
